name: agh-demo-logging-infrastructure

volumes:
  loki-data-dev:
  grafana-data-dev:

networks:
  agh-demo-logging:
    external: true

services:
  loki:
    image: grafana/loki:latest
    container_name: agh-demo-logging.loki
    networks:
      - agh-demo-logging
    ports:
      - "3100:3100"
    volumes:
      - loki-data-dev:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  grafana:
    container_name: agh-demo-logging.grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - agh-demo-logging